trigger:
  branches:
    include:
      - master
      - refs/tags/*

pr:
- master

resources:
  repositories:
    - repository: templates
      type: github
      name: CadQuery/conda-packages
      endpoint: CadQuery

jobs:
# Use the new optimized pipeline with caching
- template: build-bindings-job-new.yml
  parameters:
    name: 'Build_OCP'
    config_file: 'ocp.toml'
    conda_env_file: 'environment.devenv.yml'
    py_maj: '3'
    py_min_build:
    - '10'
    - '11'
    - '12'
    - '13'
    enable_cache: true  # Set to false for clean builds
